configurationDefinitions:
  - platform: ALL
    description: java agent configuration description - tests
    type: java-config
    version: 1.0.0
    format: yml
    schema: ./schemas/java-config.json
