configurationDefinitions:
  - platform: KUBERNESCLUSTER
    description: java agent configuration description - add commentlksjdfljsd
    type: java-config
    version: 1.0.0
    format: yml
    schema: ./schemas/java-config.json
