name: Create init-container release tags
on:
  workflow_dispatch: # Allow manual trigger
    inputs:
      agent-version:
        description: 'The release tag to create init containers for, including the v. Eg v8.12.0â€™. '
        required: true
        type: string
jobs:
  create_release_tags:
    runs-on: ubuntu-20.04
    steps:
      - name: Create release tags for K8s Init Container
        run: |
          RELEASE_TITLE="New Relic Java Agent ${{ inputs.agent-version }}.0"
          RELEASE_TAG="${{ inputs.agent-version }}.0_java"
          RELEASE_NOTES="Automated release for [Java Agent ${{ inputs.agent-version }}](https://github.com/newrelic/newrelic-java-agent/releases/tag/${{ inputs.agent-version }})"
          gh auth login --with-token <<< $GH_RELEASE_TOKEN
          echo "newrelic/newrelic-agent-init-container - Releasing \"${RELEASE_TITLE}\" with tag ${RELEASE_TAG}"
          gh release create "${RELEASE_TAG}" --title="${RELEASE_TITLE}" --repo=newrelic/newrelic-agent-init-container --notes="${RELEASE_NOTES}"
        env:
          GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
