name: Release - Copy to S3 (Staging)

on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true
        type: string
        description: 'The sonatype repo name. Eg. comnewrelic-1234'
      version_number:
        required: true
        type: string
        description: 'The version being released. Eg. 7.11.0'

jobs:
  copy-to-s3:
    name: Copy ${{ inputs.version_number }} to S3 (Staging)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Self
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        # This always checkouts main. So the script will be run from main.

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # pin@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-2

      - name: Run script
        env:
          RUNNING_ON_GHA: 'true'
        run: ./automation/release/copy-to-s3.sh ${{ inputs.repo_name }} ${{ inputs.version_number }} staging
