name: Send Slack Message

on: [workflow_dispatch]

jobs:
  send-slack:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
